import Head from "next/head";
import Hero from "../components/Hero";
import About from "../components/About";
import Banner from "../components/Banner";
import Form from "../components/Form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alvaro Castillo </title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Form />
      </main>
    </div>
  );
}
